// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: cuxmfkoaoacdximnmuuk

class SupabaseConfig {
  static const String supabaseUrl = 'https://cuxmfkoaoacdximnmuuk.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1eG1ma29hb2FjZHhpbW5tdXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ5NDM4NjAsImV4cCI6MjA4MDUxOTg2MH0.j2nD1LhOi7RwQIiUTmreygm8kUkAzzBXPhd1_q1Z0AY';
}
